#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Init Tasks
  hosts: all
  gather_facts: yes
  tasks:

  - name: Include needed global variables
    include_vars:
      file: ../default/main.yml

  - name: Include needed variables for Raspberry Pi OS
    include_vars:
      file: ../default/raspbianos.yml
    when: ansible_distribution == "Debian" and ansible_os_family == "Debian" and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l' or ansible_architecture == "aarch64")

  - name: Include needed variables for Xubuntu
    include_vars:
      file: ../default/xubuntu.yml
    when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" and (ansible_architecture == "x86_64" or ansible_architecture == "amd64")
