#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Init Tasks
  hosts: all
  gather_facts: yes
  tasks:

  - name: Include needed global variables
    include_vars:
      file: ../default/main.yml

  - name: Include needed variables for Raspberry Pi OS
    include_vars:
      file: ../default/raspbianos.yml
    when: is_rpi|bool

  - name: Include needed variables for Inovato Quadra (ARMbian)
    include_vars:
      file: ../default/inovato.yml
    when: is_iq|bool

  - name: Include needed variables for Xubuntu
    include_vars:
      file: ../default/xubuntu.yml
    when: is_pc|bool
