#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install BlueDV Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Create directory bluedv
    become: yes
    file:
      path: /usr/bluedv
      state: directory

  - name: Install BlueDV prerequisite packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - mono-complete
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Ensure the most recent ca certs are installed
    become: yes
    package:
      name: ca-certificates
      state: present
    when: is_rpi|bool and is_bullseye|bool

  - name: Remove the offending "Let's Encrypt" root cert from the root store
    become: yes
    command: mv /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt /home/{{ ham_user }}/DST_Root_CA_X3.crt 
    when: is_rpi|bool and is_bullseye|bool

  - name: Resolves warning in next step
    become: yes
    command: sed -i "/^mozilla\/DST_Root_CA_X3.crt/g" /etc/ca-certificates.conf
    when: is_rpi|bool and is_bullseye|bool

  - name: Update the root ca store -- this also updates mono
    become: yes
    command: update-ca-certificates
    when: is_rpi|bool and is_bullseye|bool

  - name: Download and Unarchive BlueDV
    become: yes
    unarchive:
      src: "{{ playbook_dir }}/../files/usr/bluedv/BlueDV_v1_0_0_9617.zip"
      dest: "/usr/bluedv"
      validate_certs: no
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

#  - name: Copy BlueDV default preferences file
#    become: yes
#    copy:
#      src: "{{ playbook_dir }}/../files/usr/bluedv/BlueDVconfig.ini"
#      dest: "/usr/bluedv/BlueDVconfig.ini"

  - name: Change owner of BlueDV folder to {{ ham_user }}
    become: yes
    file: dest=/usr/bluedv owner="{{ ham_user }}" group="{{ ham_user }}" recurse=yes

  - name: Copy BlueDV desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/applications/BlueDV.desktop"
      dest: "/usr/share/applications/BlueDV.desktop"

  - name: Modify categories for BlueDV.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/BlueDV.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio

  - name: Download latest AMBEServer sources
    git:
      repo: https://github.com/marrold/AMBEServer.git
      dest: /home/{{ ham_user }}/hamradio/AMBEServer
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Build AMBEServer
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/AMBEServer

  - name: Install AMBEServer
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/AMBEServer

  - name: Remove AMBEServer build directory
    file:
      path: /home/{{ ham_user }}/hamradio/AMBEServer
      state: absent
