#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Lopora by PA2OHH
  hosts: all
  gather_facts: no
  tasks:

  - name: Install dependent libraries for Lopora
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-numpy
      - python3-pillow
      - python3-pil.imagetk
      - python3-pyaudio
      - pulseaudio
      - pavucontrol
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory /home/{{ ham_user }}/lopora
    file:
      path: /home/{{ ham_user }}/lopora
      state: directory

#
# Download and install LOPORA
#

  - name: Download and Unarchive Lopora QRSS beacon reception program
    unarchive:
      src: https://www.qsl.net/pa2ohh/11lopsource.zip
      dest: /home/{{ ham_user }}/lopora
      remote_src: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Set quickstart script to executable
    file: dest=/home/{{ ham_user }}/lopora/scriptfiles/quickstartlopora.sh mode=a+x

  - name: Create quickstartlopora-pi.sh
    copy:
      dest: /home/{{ ham_user }}/lopora/scriptfiles/quickstartlopora-pi.sh
      mode: 0755
      content: |
        #!/bin/sh

        # Start Lopora
        cd /home/{{ ham_user }}/lopora
        lxterminal -l -e 'python3 LOPORA-v5e.py ; /bin/sh' &
        lxterminal -l -e 'python3 LOPEXTftp-v1a.py ; /bin/sh' &

  - name: Copy Lopora desktop file
    become: yes
    template:
      src: "{{ playbook_dir }}/../templates/usr/local/share/applications/lopora.desktop.j2"
      dest: "/usr/local/share/applications/lopora.desktop"
      owner: root
      group: root
      mode: 0644
