#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Digital Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Install linpsk Package (Operate PSK31/RTTY modes with X GUI)
    become: yes
    package:
      name: linpsk
      state: present
    when: ansible_distribution == "Debian" and ansible_os_family == "Debian" and ansible_distribution_major_version == "10" and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l' or ansible_architecture == "aarch64")
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Modify categories for linpsk.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/linpsk.desktop
      regexp: '^Categories=Network;HamRadio'
      line: Categories=HamRadio PSK
    when: ansible_distribution == "Debian" and ansible_os_family == "Debian" and ansible_distribution_major_version == "10" and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l' or ansible_architecture == "aarch64")

  - name: Install multimon Package (Linux Radio Transmission Decoder)
    become: yes
    package:
      name: multimon
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install psk31lx Package (PSK31 terminal application with text-based user interface)
    become: yes
    package:
      name: psk31lx
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Modify categories for psk31lx.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/psk31lx.desktop
      regexp: '^Categories=HamRadio;ConsoleOnly;Audio;AudioVideo'
      line: Categories=HamRadio PSK

  - name: Install twpsk Package (Soundcard-based X program for operating PSK31)
    become: yes
    package:
      name: twpsk
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Modify categories for twpsk.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/twpsk.desktop
      regexp: '^Categories=Network;HamRadio'
      line: Categories=HamRadio PSK
