#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Wordsworth
  hosts: all
  gather_facts: no
  tasks:

#
# Install Wordsworth
#

  - name: Create directory hamradio
    become: yes
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Download and Unarchive latest KB1OIQ - Wordsworth
    unarchive:
      src: https://sourceforge.net/projects/kb1oiq-k1ig-wordsworth/files/wordsworth/wordsworth_0.3.zip/download
      dest: /home/{{ ham_user }}/hamradio
      remote_src: yes
      validate_certs: no
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Decompress Wordsworth
    shell: gunzip *.gz
    args:
      chdir: /home/{{ ham_user }}/hamradio/wordsworth_0.3
