#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install TQSL
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libdb-dev
      - libssl-dev
      - libcurl4-openssl-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Buster)
    become: yes
    package:
      name: libwxgtk3.0-dev
      state: present
    when: is_arm|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Bullseye)
    become: yes
    package:
      name: libwxgtk3.0-gtk3-dev
      state: present
    when: is_arm|bool and is_bullseye|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Xubuntu)
    become: yes
    package:
      name: libwxgtk3.0-gtk3-dev
      state: present
    when: is_hampc|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (aarch64)
    become: yes
    package:
      name: liblmdb-dev
      state: present
    when: is_arm_64|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false


  - name: Determine latest version of TQSL on web
    shell: curl --silent "http://www.arrl.org/tqsl-download" | grep -Po "TQSL [0-9]+\.[0-9]+\.[0-9]+ for Linux" | grep -Po "[0-9]+\.[0-9]+\.[0-9]+"
    args:
      warn: no
    register: tqsl_version
    retries: 5
    delay: 30
    until: tqsl_version.failed == false

  - name: Download and Unarchive TQSL {{ tqsl_version.stdout }}
    unarchive:
      src: "http://www.arrl.org/files/file/LoTW%20Instructions/tqsl-{{ tqsl_version.stdout }}.tar.gz"
      dest: "/home/{{ ham_user }}/hamradio/"
      remote_src: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Configure TQSL {{ tqsl_version.stdout }}
    command: cmake . --install-prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/tqsl-{{ tqsl_version.stdout }}

  - name: Build TQSL {{ tqsl_version.stdout }}
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/tqsl-{{ tqsl_version.stdout }}

  - name: Install TQSL {{ tqsl_version.stdout }}
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/tqsl-{{ tqsl_version.stdout }}

  # TQSL 2.5.9 breaks the installation of the desktop file
  - name: Copy tqsl.desktop to new location since TQSL 2.5.9 make install is broken
    become: yes
    copy:
      src: "/home/{{ ham_user }}/hamradio/tqsl-{{ tqsl_version.stdout }}/apps/tqsl.desktop"
      dest: /usr/share/applications/tqsl.desktop
      remote_src: yes

  - name: Modify categories for tqsl.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/tqsl.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio Logging

  - name: Remove TQSL {{ tqsl_version.stdout }} build directory
    file:
      path: /home/{{ ham_user }}/hamradio/tqsl-{{ tqsl_version.stdout }}
      state: absent
