#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Go language
  hosts: all
  gather_facts: no
  tasks:

  - name: Download latest go sources (ARM)
    become: yes
    unarchive:
      src: https://go.dev/dl/go1.19.4.linux-armv6l.tar.gz
      dest: /usr
      remote_src: yes
    when: is_arm|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest go sources (Xubuntu)
    become: yes
    unarchive:
      src: https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
      dest: /usr
      remote_src: yes
    when: is_hampc|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

# Note: .bash_local configuration for GO added in
#  tasks/configuration_tasks.yml
