#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Open Digital Voice (OpenDV) Software
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries for OpenDV (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - automake
      - debhelper
      - libasound2-dev
      - portaudio19-dev
      - libusb-1.0-0-dev
      - fakeroot
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for OpenDV (ARM Buster)
    become: yes
    package:
      name: libwxgtk3.0-dev
      state: present
    when: is_arm|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for OpenDV (ARM Bullseye)
    become: yes
    package:
      name: libwxgtk3.0-gtk3-dev
      state: present
    when: is_arm|bool and is_bullseye|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for OpenDV (Xubuntu)
    become: yes
    package:
      name: libwxgtk3.0-gtk3-dev
      state: present
    when: is_hampc|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for OpenDV (ARM Buster)
    become: yes
    package:
      name: wiringpi
      state: present
    when: is_arm|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest OpenDV sources
    git:
      repo: https://github.com/dl5di/OpenDV.git
      dest: /home/{{ ham_user }}/hamradio/OpenDV
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

#
# AMBETools
#

  - name: Fix architecture for OpenDV - AMBETools
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools/settings.mk
      regexp: '^export ARCH := x86-64'
      line: export ARCH := native
    when: not is_x86_64|bool

  - name: Fix BINDIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools/settings.mk
      regexp: '^export BINDIR  := "/usr/local/bin"'
      line: export BINDIR  := "/usr/bin"
    when: not is_x86_64|bool

  - name: Fix DATADIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools/settings.mk
      regexp: '^export DATADIR := "/usr/local/etc"'
      line: export DATADIR := "/usr/etc"
    when: not is_x86_64|bool

  - name: Fix DESKTOPDIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools/settings.mk
      regexp: '^export DESKTOPDIR := "/usr/local/share/applications"'
      line: export DESKTOPDIR := "/usr/share/applications"
    when: not is_x86_64|bool

  - name: Fix PNGDIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools/settings.mk
      regexp: '^export PNGDIR := "/usr/local/share/pixmaps"'
      line: export PNGDIR := "/usr/share/pixmaps"
    when: not is_x86_64|bool

  - name: Build OpenDV - AMBETools
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools

  - name: Install OpenDV - AMBETools
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/AMBETools


#
# AnalogueRepeater
#
  - name: Configure OpenDV - AnalogueRepeater
    command: ./configure --prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/AnalogueRepeater

  - name: Build OpenDV - AnalogueRepeater
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/AnalogueRepeater

  - name: Install OpenDV - AnalogueRepeater
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/AnalogueRepeater


#
# Digital Voice
#

  - name: Fix architecture for OpenDV - Digital Voice
    lineinfile:
      path: "/home/{{ ham_user }}/hamradio/OpenDV/Digital Voice/settings.mk"
      regexp: '^export ARCH := x86-64'
      line: export ARCH := native
    when: not is_x86_64|bool

  - name: Fix BINDIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/Digital Voice/settings.mk
      regexp: '^export BINDIR  := "/usr/local/bin"'
      line: export BINDIR  := "/usr/bin"
    when: not is_x86_64|bool

  - name: Fix DATADIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/Digital Voice/settings.mk
      regexp: '^export DATADIR := "/usr/local/etc"'
      line: export DATADIR := "/usr/etc"
    when: not is_x86_64|bool

  - name: Fix DESKTOPDIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/Digital Voice/settings.mk
      regexp: '^export DESKTOPDIR := "/usr/local/share/applications"'
      line: export DESKTOPDIR := "/usr/share/applications"
    when: not is_x86_64|bool

  - name: Fix PNGDIR
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/OpenDV/Digital Voice/settings.mk
      regexp: '^export PNGDIR := "/usr/local/share/pixmaps"'
      line: export PNGDIR := "/usr/share/pixmaps"
    when: not is_x86_64|bool

  - name: Build OpenDV - Digital Voice
    command: make
    args:
      chdir: "/home/{{ ham_user }}/hamradio/OpenDV/Digital Voice"

  - name: Install OpenDV - Digital Voice
    become: yes
    command: make install
    args:
      chdir: "/home/{{ ham_user }}/hamradio/OpenDV/Digital Voice"


#
# DStarRepeater
#

  - name: Configure OpenDV - DStarRepeater
    command: ./configure --prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/DStarRepeater

  - name: Build OpenDV - DStarRepeater
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/DStarRepeater

  - name: Install OpenDV - DStarRepeater
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/DStarRepeater


#
# DummyRepeater
#

  - name: Configure OpenDV - DummyRepeater
    command: ./configure --prefix=/usr --with-ambeserver
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/DummyRepeater

  - name: Build OpenDV - DummyRepeater
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/DummyRepeater

  - name: Install OpenDV - DummyRepeater
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/DummyRepeater


#
# ircDDBGateway
#

  - name: Configure OpenDV - ircDDBGateway
    command: ./configure --prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/ircDDBGateway

  - name: Build OpenDV - ircDDBGateway
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/ircDDBGateway

  - name: Install OpenDV - ircDDBGateway
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/ircDDBGateway


#
# XReflector
#

  - name: Configure OpenDV - XReflector
    command: ./configure --prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflector

  - name: Build OpenDV - XReflector
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflector

  - name: Install OpenDV - XReflector
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflector

# Work around a Git issue -- missing libircDDB.a file
  - name: Build OpenDV - XReflectorDaemon
    command: cp libircDDB.a ../ircDDB
    args:
      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflector


#
# There are some basic compilation errors which are outside my focus of
# creating the image to work around. These affect XReflectorDaemon and
# RepeaterExtras - djs 2020-06-07
#

#
# XReflectorDaemon
#

## Work around a Git issue -- missing IRCDDB.h file
#  - name: Build OpenDV - XReflectorDaemon
#    command: cp /home/{{ ham_user }}/hamradio/OpenDV/XReflector/ircDDB/IRCDDB.h Common
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflectorDaemon
#
#  - name: Build OpenDV - XReflectorDaemon
#    command: make
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflectorDaemon
#
#  - name: Install OpenDV - XReflectorDaemon
#    become: yes
#    command: make install
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/OpenDV/XReflectorDaemon
#

##
## RepeaterExtras
##
#
#  - name: Build OpenDV - RepeaterExtras
#    command: make
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/OpenDV/RepeaterExtras
#
#  - name: Install OpenDV - RepeaterExtras
#    become: yes
#    command: make install
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/OpenDV/RepeaterExtras

#
# Common
#
  - name: Remove OpenDV build directory
    file:
      path: /home/{{ ham_user }}/hamradio/OpenDV
      state: absent
