#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install PMON
  hosts: all
  gather_facts: no
  tasks:

  - name: Create hamradio directory
    file:
      path: /home/{{ ham_user }}/hamradio/
      state: directory

  - name: Add SCS APT Repository
    become: yes
    shell: echo "deb https://www.scs-ptc.com/repo/packages/ buster non-free" > /etc/apt/sources.list.d/scs.list

  - name: Add SCS GPG Key
    become: yes
    shell: wget -q -O - https://www.scs-ptc.com/repo/packages/scs.gpg.key | apt-key add -
    args:
      warn: no
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Update APT repo sources
    become: yes
    apt:
      update_cache: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install PMON (ARM) - PACTOR Monitoring Utility for Linux
    become: yes
    apt:
      name: pmon
      state: present
    when: is_arm|bool and not is_arm_64|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false
