#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Ten Ten QSO Logger
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Install Ten Ten QSO Logger pre-requisites
    become: yes
    package:
      name: default-jre
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory /usr/1010qsologger
    become: yes
    file:
      path: /usr/1010qsologger
      state: directory

  - name: Download and Unarchive Ten Ten QSO Logger
    become: yes
    unarchive:
      src: "https://n7yg.net/files/10qsolog.zip"
      dest: /usr/1010qsologger
      remote_src: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Remove Ten Ten QSO Logger cruft
    become: yes
    shell: rm 10QSOLogger.exe 10qsolog.bat
    args:
      chdir: /usr/1010qsologger
      warn: no

  - name: Change /usr/1010qsologger/10qsolog.sh to Executable
    become: yes
    file: dest=/usr/1010qsologger/10qsolog.sh mode=a+x

  - name: Copy Ten Ten QSO Logger desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/applications/tentenlogger.desktop"
      dest: "/usr/share/applications/tentenlogger.desktop"
