#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install QSSTV
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - g++
      - libfftw3-dev
      - libpulse-dev
      - libhamlib-dev
      - libasound2-dev
      - libv4l-dev
      - libopenjp2-7
      - libopenjp2-7-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Raspberry Pi Buster)
    become: yes
    package:
      name: qt5-default
      state: present
    when: is_rpi|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Determine latest version of QSSTV on web
    shell: curl --silent "http://users.telenet.be/on4qz/qsstv/downloads/" | grep -Po "[0-9]+\.[0-9]+\.[0-9]+" | uniq | tail -n 1
    args:
      warn: no
    register: download_date

  - name: Download and Unarchive QSSTV {{ download_date.stdout }}
    unarchive:
      src: "http://users.telenet.be/on4qz/qsstv/downloads/qsstv_{{ download_date.stdout }}.tar.gz"
      dest: "/home/{{ ham_user }}/hamradio/"
      remote_src: yes

  - name: Normalize QSSTV directory name {{ download_date.stdout }}
    shell: mv qsstv* "qsstv_{{ download_date.stdout }}"
    ignore_errors: yes
    args:
      chdir: "/home/{{ ham_user }}/hamradio/"

  - name: Build QSSTV Makefile {{ download_date.stdout }}
    command: qmake
    args:
      chdir: "/home/{{ ham_user }}/hamradio/qsstv_{{ download_date.stdout }}"

  - name: Build QSSTV {{ download_date.stdout }}
    command: make
    args:
      chdir: "/home/{{ ham_user }}/hamradio/qsstv_{{ download_date.stdout }}"

  - name: Install QSSTV {{ download_date.stdout }}
    become: yes
    command: make install
    args:
      chdir: "/home/{{ ham_user }}/hamradio/qsstv_{{ download_date.stdout }}"

  - name: Modify categories for qsstv.desktop
    lineinfile:
      path: "/home/{{ ham_user }}/hamradio/qsstv_{{ download_date.stdout }}/qsstv.desktop"
      regexp: '^Categories=Education;'
      line: Categories=HamRadio

  - name: Copy qsstv.desktop to /usr/local/share/applications
    become: yes
    copy:
      src: "/home/{{ ham_user }}/hamradio/qsstv_{{ download_date.stdout }}/qsstv.desktop"
      dest: /usr/local/share/applications/qsstv.desktop
      remote_src: yes

  - name: Remove QSSTV {{ download_date.stdout }} build directory
    file:
      path: /home/{{ ham_user }}/hamradio/qsstv_{{ download_date.stdout }}
      state: absent
