#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install RtAudio library
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

#
# Build and install RtAudio (CMake 3.10 is a pre-requisite for building RtAudio)
#

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - automake
      - libjack0
      - libjack-dev
      - libpulse-dev
      - libasound2-dev
      - libfftw3-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest RtAudio sources
    git:
      repo: https://github.com/thestk/rtaudio.git
      dest: /home/{{ ham_user }}/hamradio/rtaudio
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: RtAudio is broken in main branch (Dec. 2021), so compensate
    command: git checkout "5.1.0"
    args:
      chdir: /home/{{ ham_user }}/hamradio/rtaudio

  - name: Create directory rtaudio/build
    file:
      path: /home/{{ ham_user }}/hamradio/rtaudio/build
      state: directory

  - name: Build RtAudio CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/rtaudio/build

  - name: Build RtAudio
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/rtaudio/build

  - name: Install RtAudio
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/rtaudio/build

  - name: Remove RtAudio build directory
    file:
      path: /home/{{ ham_user }}/hamradio/rtaudio
      state: absent
