#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SKCCLogger
  hosts: all
  gather_facts: no
  tasks:

#
# ARM
#

  - name: Copy SKCCLogger from local file (because developer moved download behind a login) (ARM)
    copy:
      src: "{{ playbook_dir }}/../files/SKCCLogger_Linux_32-Bit-ARM.zip"
      dest: "/home/{{ ham_user }}/hamradio/SKCCLogger_Linux_32-Bit-ARM.zip"
    when: is_arm|bool and not is_arm_64|bool

  - name: Unarchive SKCCLogger (ARM)
    become: yes
    unarchive:
      src: "/home/{{ ham_user }}/hamradio/SKCCLogger_Linux_32-Bit-ARM.zip"
      dest: /usr
      remote_src: yes
    when: is_arm|bool and not is_arm_64|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Change Ownership of /usr/SKCCLogger_Linux_32-Bit-ARM to {{ ham_user }}
    become: yes
    file: dest=/usr/SKCCLogger_Linux_32-Bit-ARM owner={{ ham_user }} group={{ ham_user}} mode=775
    when: is_arm|bool and not is_arm_64|bool

  - name: Change Ownership of /usr/SKCCLogger_Linux_32-Bit-ARM to {{ ham_user }}
    become: yes
    shell: chown -R {{ ham_user }}.{{ ham_user }} /usr/SKCCLogger_Linux_32-Bit-ARM
    args:
      warn: false
    when: is_arm|bool and not is_arm_64|bool

  - name: Remove SKCCLogger from local file (ARM)
    file:
      path: "/home/{{ ham_user }}/hamradio/SKCCLogger_Linux_32-Bit-ARM.zip"
      state: absent
    when: is_arm|bool and not is_arm_64|bool

#
# Xubuntu
#
  - name: Copy SKCCLogger from local file (because developer moved download behind a login) (Xubuntu)
    copy:
      src: "{{ playbook_dir }}/../files/SKCCLogger_Linux_64-Bit.zip"
      dest: "/home/{{ ham_user }}/hamradio/SKCCLogger_Linux_64-Bit.zip"
    when: is_hampc|bool

  - name: Unarchive SKCCLogger (Xubuntu)
    become: yes
    unarchive:
      src: "/home/{{ ham_user }}/hamradio/SKCCLogger_Linux_64-Bit.zip"
      dest: /usr
      remote_src: yes
    when: is_hampc|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Change Ownership of /usr/SKCCLogger_Linux_64-Bit to {{ ham_user }}
    become: yes
    file: dest=/usr/SKCCLogger_Linux_64-Bit owner={{ ham_user }} group={{ ham_user}} mode=775
    when: is_hampc|bool

  - name: Change Ownership of /usr/SKCCLogger_Linux_64-Bit to {{ ham_user }}
    become: yes
    shell: chown -R {{ ham_user }}.{{ ham_user }} /usr/SKCCLogger_Linux_64-Bit
    args:
      warn: false
    when: is_hampc|bool

  - name: Remove SKCCLogger from local file (Xubuntu)
    file:
      path: "/home/{{ ham_user }}/hamradio/SKCCLogger_Linux_64-Bit.zip"
      state: absent
    when: is_hampc|bool
