#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Antenna Modeling Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Install Antenna Modeling Packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - antennavis
      - nec2c
      - splat
      - xnec2c
      - xnecview
      - yagiuda

  - name: Install Antenna Modeling Packages (not 64-bit ARM)
    become: yes
    package:
      name: gsmc
      state: present
    when: ansible_architecture != "aarch64"

  - name: Copy desktop file for Antenna Visualizer
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/local/share/applications/antennavis.desktop"
      dest: "/usr/local/share/applications/antennavis.desktop"

  # GTK Smith Chart Calculator (not 64-bit ARM)
  - name: Modify categories for gsmc.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/gsmc.desktop
      regexp: '^Categories=Education;HamRadio;'
      line: Categories=HamRadio Calculators
    when: ansible_architecture != "aarch64"

  - name: Modify categories for nec2c.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/nec2c.desktop
      regexp: '^Categories=Network;HamRadio;X-HamRadio-Antennas'
      line: Categories=HamRadio Antenna Analyzer

  - name: Modify categories for xnec2c.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/xnec2c.desktop
      regexp: '^Categories=Science;Math;NumericalAnalysis;'
      line: Categories=HamRadio Antenna Analyzer
