#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install flamp
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

    - name: Create directory hamradio
      file:
        path: /home/{{ ham_user }}/hamradio/
        state: directory

    - name: Install dependent libraries
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - libfltk1.3-dev
        - libcurl4-openssl-dev
      retries: 5
      delay: 30
      register: result
      until: result.failed == false

    - name: Determine latest version of flamp on web
      shell: curl --silent "http://www.w1hkj.com/files/flamp/" | grep -Po "[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz" | grep -Po "[0-9]+\.[0-9]+\.[0-9]+" | uniq | tail -n 1
      args:
        warn: no
      register: download_date
      retries: 5
      delay: 30
      until: download_date.failed == false

    - name: Download and Unarchive flamp {{ download_date.stdout }}
      unarchive:
        src: http://www.w1hkj.com/files/flamp/flamp-{{ download_date.stdout }}.tar.gz
        dest: /home/{{ ham_user }}/hamradio/
        remote_src: yes
      retries: 5
      delay: 30
      register: result
      until: result.failed == false

    - name: Configure flamp {{ download_date.stdout }}
      command: ./configure
      args:
        chdir: /home/{{ ham_user }}/hamradio/flamp-{{ download_date.stdout }}

    - name: Build flamp {{ download_date.stdout }}
      command: make all
      args:
        chdir: /home/{{ ham_user }}/hamradio/flamp-{{ download_date.stdout }}

    - name: Install flamp {{ download_date.stdout }}
      become: yes
      command: make install
      args:
        chdir: /home/{{ ham_user }}/hamradio/flamp-{{ download_date.stdout }}

    - name: Modify categories for flamp.desktop
      become: yes
      lineinfile:
        path: /usr/local/share/applications/flamp.desktop
        regexp: '^Categories=Network;HamRadio;'
        line: Categories=HamRadio Fldigi

    - name: Remove flamp {{ download_date.stdout }} build directory
      file:
        path: /home/{{ ham_user }}/hamradio/flamp-{{ download_date.stdout }}
        state: absent
