#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install D-Rats
  hosts: all
  gather_facts: no
  tasks:

  - name: Download D-Rats sources from John and Maurizio's GitHub
    git:
      repo: https://github.com/ham-radio-software/D-Rats.git
      dest: /home/{{ ham_user }}/hamradio/D-Rats
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install D-Rats update script
    become: yes
    template:
      src: "{{ playbook_dir }}/../templates/usr/local/bin/update_d-rats.j2"
      dest: "/usr/local/bin/update_d-rats"
      mode: a+x

  - name: Modify categories for d-rats.desktop
    become: yes
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/D-Rats/share/d-rats.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio D-Rats

  - name: Modify categories for d-rats_repeater.desktop
    become: yes
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/D-Rats/share/d-rats_repeater.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio D-Rats

  - name: Run D-Rats update script (which builds and installs D-Rats from Git)
    command: /usr/local/bin/update_d-rats

  - name: Copy D-Rats update script desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/local/share/applications/update-drats.desktop"
      dest: "/usr/local/share/applications/update-drats.desktop"
