#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install JTDX
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent components
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-pip
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent components (Raspberry Pi Bullseye ARM)
    become: yes
    package:
      name: libgfortran5
      state: present
    when: is_rpi|bool and is_bullseye|bool and is_arm|bool
    retries: 5
    delay: 30
    register: result

  - name: Install dependent components (Raspberry Pi Bullseye)
    become: yes
    package:
      name: libgfortran4
      state: present
    when: is_rpi|bool and is_bullseye|bool and not is_arm|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent components (AMD64 Xubuntu/Ubuntu 20)
    become: yes
    package:
      name: libqt5websockets5
      state: present
    when: (ansible_architecture == "x86_64" or ansible_architecture == "amd64") and ansible_distribution_major_version >= "20"
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

#
# Common
#

  - name: Git clone latest JTDX sources
    git:
      repo: https://www.github.com/jtdx-project/jtdx
      dest: /home/{{ ham_user }}/hamradio/jtdx
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory jtdx/build
    file:
      path: /home/{{ ham_user }}/hamradio/jtdx/build
      state: directory

  - name: Build Dev JTDX CMakeFiles
    command: cmake .. -DWSJT_SKIP_MANPAGES=ON
    args:
      chdir: /home/{{ ham_user }}/hamradio/jtdx/build

  - name: Build JTDX
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/jtdx/build

  - name: Install JTDX
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/jtdx/build

  - name: Modify categories for jtdx.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/jtdx.desktop
      regexp: '^Categories=AudioVideo;Audio;HamRadio;'
      line: Categories=HamRadio Weak Signal

  - name: Remove JTDX build directory
    file:
      path: /home/{{ ham_user }}/hamradio/jtdx
      state: absent
