#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install HamClock Software
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libmotif-dev
      - libcurl4-openssl-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download and Unarchive HamClock by WB0OEW
    unarchive:
      src: https://www.clearskyinstitute.com/ham/HamClock/ESPHamClock.zip
      dest: /home/{{ ham_user }}/hamradio
      remote_src: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Build HamClock by WB0OEW
    command: make hamclock-800x480
    args:
      chdir: /home/{{ ham_user }}/hamradio/ESPHamClock

  - name: Install HamClock application by WB0OEW
    become: yes
    command: cp hamclock-800x480 /usr/local/bin
    args:
      chdir: /home/{{ ham_user }}/hamradio/ESPHamClock

  - name: Install HamClock icon
    become: yes
    command: cp hamclock.png /usr/local/share/icons
    args:
      chdir: /home/{{ ham_user }}/hamradio/ESPHamClock

  - name: Copy HamClock desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/local/share/applications/hamclock.desktop"
      dest: "/usr/local/share/applications/hamclock.desktop"

  - name: Remove HamClock by WB0OEW build directory
    file:
      path: /home/{{ ham_user }}/hamradio/ESPHamClock
      state: absent
