#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install PyBOMBS (Used by GnuRadio)
  hosts: all
  tasks:

  # Use this for Python3
  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-pip

  - name: Install Python module - PyBOMBS
    become: yes
    command: pip3 install --upgrade git+https://github.com/gnuradio/pybombs.git