#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install QSLWare nag dialog
  hosts: all
  gather_facts: no
  tasks:

#
# ARM
#
  - name: Create directory lxsession/LXDE-pi
    file:
      path: /home/{{ ham_user }}/.config/lxsession/LXDE-pi
      state: directory
    when: is_arm|bool

  - name: Install executable QSLware nag script
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/lxsession/LXDE-pi/qslware.sh"
      dest: "/home/{{ ham_user }}/.config/lxsession/LXDE-pi/qslware.sh"
      mode: a+x
    when: is_arm|bool

  - name: Install lxsession autostart
    template:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/lxsession/LXDE-pi/autostart"
      dest: "/home/{{ ham_user }}/.config/lxsession/LXDE-pi/autostart"
    when: is_arm|bool

  - name: Install remove script
    template:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/lxsession/LXDE-pi/remove_nag_dialog"
      dest: "/home/{{ ham_user }}/.config/lxsession/LXDE-pi/remove_nag_dialog"
      mode: a+x
    when: is_arm|bool

#
# Xubuntu - X86
#
  - name: Create directory .config/autostart
    file:
      path: /home/{{ ham_user }}/.config/autostart
      state: directory
    when: is_hampc|bool

  - name: Install executable QSLware nag script
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/autostart/qslware.desktop"
      dest: "/home/{{ ham_user }}/.config/autostart/qslware.desktop"
    when: is_hampc|bool

  - name: Install remove script
    copy:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/autostart/remove_nag_dialog"
      dest: "/home/{{ ham_user }}/.config/autostart/remove_nag_dialog"
      mode: a+x
    when: is_hampc|bool
