#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install NOAA APT Software
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libgtk-3-dev
      - libssl-dev

  - name: Download RUST installer
    shell: /usr/bin/curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/initrust.sh
    args:
      chdir: /home/{{ ham_user }}/hamradio

  - name: Set RUST installer to executable
    file: dest=/tmp/initrust.sh mode=755

  - name: Install RUST from script
    shell: /tmp/initrust.sh -y

  - name: Git clone latest noaa-apt sources
    git:
      repo: https://github.com/martinber/noaa-apt.git
      dest: /home/{{ ham_user }}/hamradio/noaa-apt
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Build noaa-apt
    command: /home/{{ ham_user }}/.cargo/bin/cargo build --release
    args:
      chdir: /home/{{ ham_user }}/hamradio/noaa-apt

  - name: Copy noaa-apt desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/local/share/applications/noaa-apt.desktop"
      dest: "/usr/local/share/applications/noaa-apt.desktop"

  - name: Remove RUST installer
    file: dest=/tmp/initrust.sh state=absent
