#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install CygnusRFI Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent components for CygnusRFI (Buster)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gnuradio-dev
      - gr-osmosdr
    retries: 5
    delay: 30
    register: result
    until: result.failed == false
    when: is_buster|bool

  - name: Install dependent components for CygnusRFI (Bullseye)
    become: yes
    package:
      name: python2.7
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false
    when: is_bullseye|bool

#
# Download CygnusRFI
#

  - name: Download latest CygnusRFI sources
    git:
      repo: https://github.com/0xCoto/CygnusRFI
      dest: /home/{{ ham_user }}/hamradio/CygnusRFI
    retries: 5
    delay: 30
    register: result
    until: result.failed == false
