#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install BOINC Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Install BOINC Packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - boinc
      - boinctui
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory boinc-client
    become: yes
    file:
      path: /etc/boinc-client
      state: directory

  - name: Change Ownership of /etc/boinc-client to boinc
    become: yes
    file: dest=/etc/boinc-client owner=boinc group=boinc

  - name: Make BOINC run a little nicer 1
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/etc/boinc-client/cc_config.xml"
      dest: "/etc/boinc-client/cc_config.xml"

  - name: Make BOINC run a little nicer 2
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/etc/boinc-client/global_prefs_override.xml"
      dest: "/etc/boinc-client/global_prefs_override.xml"

  - name: Change Ownership of /etc/boinc-client to boinc
    become: yes
    file: dest=/etc/boinc-client owner=boinc group=boinc

  - name: Change Ownership of /etc/boinc-client/cc_config.xml to boinc
    become: yes
    file: dest=/etc/boinc-client/cc_config.xml owner=boinc group=boinc

  - name: Change Ownership of /etc/boinc-client/global_prefs_override.xml to boinc
    become: yes
    file: dest=/etc/boinc-client/global_prefs_override.xml owner=boinc group=boinc

  - name: Create /home/{{ ham_user }}/.config/lxsession/LXDE-pi directory
    file:
      path: /home/{{ ham_user }}/.config/lxsession/LXDE-pi
      state: directory
    when: is_hampi|bool

  - name: Install BOINC script
    copy:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/lxsession/LXDE-pi/boinc.sh"
      dest: "/home/{{ ham_user }}/.config/lxsession/LXDE-pi/boinc.sh"
      mode: a+x
    when: is_hampi|bool

#
# Xubuntu
#

  - name: Create /home/{{ ham_user }}/.config/autostart directory
    file:
      path: /home/{{ ham_user }}/.config/autostart
      state: directory
    when: is_hampc|bool

  - name: Install BOINC autostart
    copy:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/autostart/boinc.desktop"
      dest: "/home/{{ ham_user }}/.config/autostart/boinc.desktop"
    when: is_hampc|bool

  - name: Install BOINC script
    copy:
      src: "{{ playbook_dir }}/../files/home/{{ ham_user }}/.config/autostart/boinc.sh"
      dest: "/home/{{ ham_user }}/.config/autostart/boinc.sh"
      mode: a+x
    when: is_hampc|bool
