#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install LySDR Software
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - autoconf
      - automake
      - autotools-dev
      - libgtk-3-dev
      - libjack-jackd2-dev
      - libfftw3-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest lysdr sources
    git:
      repo: https://github.com/gordonjcp/lysdr.git
      dest: /home/{{ ham_user }}/hamradio/lysdr
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Run autoreconf for lysdr
    command: autoreconf -i
    args:
      chdir: /home/{{ ham_user }}/hamradio/lysdr

  - name: Configure lysdr
    command: ./configure --prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/lysdr

  - name: Build lysdr
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/lysdr

  - name: Install lysdr
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/lysdr

  - name: Remove lysdr build directory
    file:
      path: /home/{{ ham_user }}/hamradio/lysdr
      state: absent
