#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install CMake Software
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Remove pre-installed cmake
    become: yes
    package:
      name: cmake
      state: absent
  
  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libssl-dev
      - curl
      - gcc
      - build-essential
      - unzip
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Buster)
    become: yes
    package:
      name: qt4-qmake
      state: present
    when: is_arm|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Bullseye)
    become: yes
    package:
      name: qt5-qmake
      state: present
    when: is_arm|bool and is_bullseye|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Xubuntu)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - qt5-qmake
    when: is_hampc|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

#
# Build and install CMake
#

  - name: Determine latest version of CMake on GitHub
    shell: curl --silent "https://github.com/Kitware/CMake/releases/" | grep -Po "cmake-[0-9]+.[0-9]+.[0-9]+.*.tar.gz" | head -n 1 | grep -Po "[0-9]+.[0-9]+.[0-9]+"
    args:
      warn: no
    retries: 5
    delay: 30
    register: cmake_version
    until: cmake_version.failed == false

  - name: Download and Unarchive CMake {{ cmake_version.stdout }} sources from https.//github.com/Kitware/CMake/releases/download/v{{ cmake_version.stdout }}/cmake-{{ cmake_version.stdout }}.tar.gz
    unarchive:
      src: https://github.com/Kitware/CMake/releases/download/v{{ cmake_version.stdout }}/cmake-{{ cmake_version.stdout }}.tar.gz
      dest: /home/{{ ham_user }}/hamradio
      remote_src: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Configure CMake {{ cmake_version.stdout }}
    command: ./configure --prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}

  - name: Build CMake {{ cmake_version.stdout }}
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}

  - name: Install CMake {{ cmake_version.stdout }}
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}

  - name: Remove CMake {{ cmake_version.stdout }} build directory
    file:
      path: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}
      state: absent
