#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install GridTracker
  hosts: all
  gather_facts: no
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio/
      state: directory

# 2020-09-19 - GridTracker has gone to an online documentation model
#  - name: Create directory for documentation
#    become: yes
#    file:
#      path: /usr/share/doc/gridtracker
#      state: directory
#
#  - name: Download GridTracker Documentation
#    become: yes
#    get_url:
#      url: https://www.dropbox.com/s/nmgqszm4t85mrg2/GTQS_0406.pdf?dl=1
#      dest: /usr/share/doc/gridtracker/GTQS_0406.pdf
#      validate_certs: no

#
# Raspbian ARM
#

#  - name: Determine latest version of GridTracker (ARM) on web
#    shell: curl --silent "https://gridtracker.org/downloads" | grep -Po "https:\/\/.*GridTracker-.*-linux-arm32.tar.gz\"" | uniq | head -n 1 | grep -Po "https:\/\/.*GridTracker-.*-linux-arm32.tar.gz"
#    args:
#      warn: no
#    register: download_file
#    when: is_arm|bool
#    retries: 5
#    delay: 30
#    until: download_file.failed == false

  - name: Download and Unarchive GridTracker (ARM)
    become: yes
    unarchive:
#      src: "{{ download_file.stdout }}"
      src: "https://storage.googleapis.com/gt_download/v1.21.0503-2/GridTracker-1.22.0503-linux-arm32.tar.gz"
#      src: "https://downloads.gridtracker.org/v1.22.1016-Harvest/GridTracker-1.22.1016-linux-arm64.tar.gz"
      dest: /usr
      remote_src: yes
    when: is_arm|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Rename GridTracker directory
    become: yes
    shell: mv /usr/GridTracker* /usr/GridTracker
    when: is_arm|bool

  - name: Copy GridTracker Desktop file (ARM)
    become: yes
    copy:
      src: /usr/GridTracker/GridTracker.desktop
      dest: /usr/share/applications/GridTracker.desktop
      remote_src: yes
    when: is_arm|bool

  - name: Fix the lazy path that GridTracker uses to what we're using
    become: yes
    replace:
      path: /usr/share/applications/GridTracker.desktop
      regexp: "/home/{{ ham_user }}/Downloads"
      replace: '/usr'
    when: is_arm|bool

  - name: Modify categories for GridTracker.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/GridTracker.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio Weak Signal
    when: is_arm|bool

#
# Raspbian x86
#

#  - name: Determine latest version of GridTracker (x86) on web
#    shell: curl --silent "https://download.gridtracker.org/latest_release.html" | grep -Po "https:\/\/.*GridTracker-linux-x86-.*.tar.gz\?dl=1"
#    args:
#      warn: no
#    register: download_file
#    when: is_i386|bool
#    retries: 5
#    delay: 30
#    until: download_file.failed == false

  - name: Download and Unarchive GridTracker (x86)
    become: yes
    unarchive:
#      src: "{{ download_file.stdout }}"
      src: "https://storage.googleapis.com/gt_download/v1.21.0503-2/GridTracker-1.22.0503-linux-x86.tar.gz"
      dest: /usr
      remote_src: yes
    when: is_i386|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Copy GridTracker Desktop file (x86)
    become: yes
    copy:
      src: /usr/GridTracker/GridTracker.desktop
      dest: /usr/share/applications/GridTracker.desktop
      remote_src: yes
    when: is_i386|bool

  - name: Fix the lazy path that GridTracker uses to what we're using
    become: yes
    replace:
      path: /usr/share/applications/GridTracker.desktop
      regexp: '~\/Downloads'
      replace: '/usr'
    when: is_i386|bool

  - name: Modify categories for GridTracker.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/GridTracker.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio Weak Signal
    when: is_i386|bool

#
# AMD64
#

#  - name: Determine latest version of GridTracker (AMD64) on web
#    shell: curl --silent "https://download.gridtracker.org/latest_release.html" | grep -Po "https:\/\/.*GridTracker-.*-linux-x64.tar.gz\"" | uniq | head -n 1 | grep -Po "https:\/\/.*GridTracker-.*-linux-x64.tar.gz"
#    args:
#      warn: no
#    register: download_file
#    when: is_x86_64|bool
#    retries: 5
#    delay: 30
#    until: download_file.failed == false

  - name: Download and Unarchive GridTracker (AMD64)
    become: yes
    unarchive:
#      src: "{{ download_file.stdout }}"
      src: "https://storage.googleapis.com/gt_download/v1.22.0725/GridTracker-1.22.0725-linux-x64.tar.gz"
      dest: /usr
      remote_src: yes
    when: is_x86_64|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Rename GridTracker directory
    become: yes
    shell: mv /usr/GridTracker* /usr/GridTracker
    when: is_x86_64|bool

#
# GridTracker Desktop file
#

  - name: Copy GridTracker Desktop file
    become: yes
    copy:
      src: /usr/GridTracker/GridTracker.desktop
      dest: /usr/share/applications/GridTracker.desktop
      remote_src: yes
    when: not is_jammy|bool

  - name: Copy GridTracker desktop file (Jammy)
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/applications/GridTracker.desktop"
      dest: "/usr/share/applications/GridTracker.desktop"
    when: is_jammy|bool

  - name: Fix the lazy path that GridTracker uses to what we're using
    become: yes
    replace:
      path: /usr/share/applications/GridTracker.desktop
      regexp: '/home/{{ ham_user }}/Downloads'
      replace: '/usr'
    when: not is_jammy|bool

  - name: Modify categories for GridTracker.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/GridTracker.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio Weak Signal
    when: not is_jammy|bool
