#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install CubicSDR Software
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - automake
      - libliquid-dev
      - libpulse-dev
      - libgtk-3-dev
      - freeglut3
      - freeglut3-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

#
# Build and install liquid-dsp
#

  - name: Git clone latest liquid-dsp sources
    git:
      repo: https://github.com/jgaeddert/liquid-dsp
      dest: /home/{{ ham_user }}/hamradio/liquid-dsp
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Bootstrap liquid-dsp
    command: ./bootstrap.sh
    args:
      chdir: /home/{{ ham_user }}/hamradio/liquid-dsp

  - name: Configure liquid-dsp
    shell: CFLAGS="-march=native -O3" ./configure --prefix=/usr --enable-fftoverride
    args:
      chdir: /home/{{ ham_user }}/hamradio/liquid-dsp

  - name: Make liquid-dsp
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/liquid-dsp

  - name: Install liquid-dsp
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/liquid-dsp

  - name: Configure dynamic linker run-time bindings
    become: yes
    command: ldconfig

  - name: Remove liquid-dsp build directory
    file:
      path: /home/{{ ham_user }}/hamradio/liquid-dsp
      state: absent

#
# Build and install CubicSDR
#

  - name: Git clone latest CubicSDR sources
    git:
      repo: https://github.com/cjcliffe/CubicSDR.git
      dest: /home/{{ ham_user }}/hamradio/CubicSDR
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Patch FILPATHLEN to HAMLIB_FILPATHLEN for newer version of HamLib
    command: sed 's/FILPATHLEN/HAMLIB_FILPATHLEN/' -i "/home/{{ ham_user }}/hamradio/CubicSDR/src/rig/RigThread.cpp"
    args:
      warn: no

  - name: Create directory CubicSDR/build
    file:
      path: /home/{{ ham_user }}/hamradio/CubicSDR/build
      state: directory

  - name: Build CubicSDR CMakeFiles
    command: cmake ../ -DCMAKE_BUILD_TYPE=Release -DUSE_HAMLIB=1 -DwxWidgets_CONFIG_EXECUTABLE=~/hamradio/wxWidgets-staticlib/bin/wx-config --install-prefix=/usr
    args:
      chdir: /home/{{ ham_user }}/hamradio/CubicSDR/build

  - name: Build CubicSDR
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/CubicSDR/build

  - name: Install CubicSDR
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/CubicSDR/build

  - name: Modify categories for CubicSDR.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/CubicSDR.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio SDR

  - name: Remove CubicSDR build directory
    file:
      path: /home/{{ ham_user }}/hamradio/CubicSDR
      state: absent
