#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install CMake Software
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Remove pre-installed cmake
    become: yes
    package:
      name: cmake
      state: absent
  
  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libssl-dev
      - curl
      - gcc
      - build-essential
      - unzip
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Raspberry Pi Buster)
    become: yes
    package:
      name: qt4-qmake
      state: present
    when: ansible_distribution == "Debian" and ansible_os_family == "Debian" and ansible_distribution_major_version == "10" and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l' or ansible_architecture == "aarch64")
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Raspberry Pi Bullseye)
    become: yes
    package:
      name: qt5-qmake
      state: present
    when: ansible_distribution == "Debian" and ansible_os_family == "Debian" and ansible_distribution_major_version == "11" and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l' or ansible_architecture == "aarch64")
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Xubuntu)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - qt5-qmake
    when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" and (ansible_architecture == "x86_64" or ansible_architecture == "amd64")
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

#
# Build and install CMake
#

  - name: Determine latest version of CMake on GitHub
    shell: curl --silent "https://github.com/Kitware/CMake/releases/" | grep -Po "cmake-[0-9]+.[0-9]+.[0-9]+.*.tar.gz" | head -n 1 | grep -Po "[0-9]+.[0-9]+.[0-9]+"
    args:
      warn: no
    retries: 5
    delay: 30
    register: cmake_version
    until: cmake_version.failed == false

  - name: Download and Unarchive CMake {{ cmake_version.stdout }} sources
    unarchive:
      src: https://github.com/Kitware/CMake/releases/download/v{{ cmake_version.stdout }}-rc3/cmake-{{ cmake_version.stdout }}-rc3.tar.gz
      dest: /home/{{ ham_user }}/hamradio
      remote_src: yes
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Configure CMake {{ cmake_version.stdout }}-rc3
    command: ./configure
    args:
      chdir: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}-rc3

  - name: Build CMake {{ cmake_version.stdout }}-rc3
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}-rc3

  - name: Install CMake {{ cmake_version.stdout }}-rc3
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}-rc3

  - name: Remove CMake {{ cmake_version.stdout }}-rc3 build directory
    file:
      path: /home/{{ ham_user }}/hamradio/cmake-{{ cmake_version.stdout }}-rc3
      state: absent
