#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Logging Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Install Prerequisite (python3-pip)
    become: yes
    package:
      name: python3-pip
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false
#    when: inovato|bool

  - name: Install Logging Packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - tlf
      - klog
      - xlog
      - cqrlog
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Modify categories for cqrlog.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/cqrlog.desktop
      regexp: '^Categories=Utility;Database;HamRadio'
      line: Categories=HamRadio Logging

  - name: Modify categories for xlog.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/xlog.desktop
      regexp: '^Categories=Utility;Database;HamRadio;GTK'
      line: Categories=HamRadio Logging

  - name: Copy klog desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/local/share/applications/klog.desktop"
      dest: "/usr/local/share/applications/klog.desktop"

#
# Logging helpers by W3DJS
#

  - name: Create /home/{{ ham_user }}/bin
    file:
      path: /home/{{ ham_user }}/bin
      state: directory

  - name: Download wsjtx_to_n3fjp executable by W3DJS
    get_url:
      url: https://raw.githubusercontent.com/dslotter/wsjtx_to_n3fjp/master/wsjtx_to_n3fjp.py
      dest: /home/{{ ham_user }}/bin/wsjtx_to_n3fjp.py
      mode: a+x
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download wsjtx_to_n3fjp default config
    get_url:
      url: https://raw.githubusercontent.com/dslotter/wsjtx_to_n3fjp/master/config
      dest: /home/{{ ham_user }}/bin/config
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install upload_adif_log dependencies
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - curl
      - espeak
      - ruby-notify
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download upload_adif_log executable by W3DJS
    get_url:
      url: https://raw.githubusercontent.com/dslotter/upload_adif_log/master/upload_adif_log
      dest: /home/{{ ham_user }}/bin/upload_adif_log
      mode: a+x
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install Tucnak2 (Raspberry Pi Buster)
    become: yes
    package:
      name: tucnak2
      state: present
    when: is_rpi|bool and is_buster|bool

  - name: Modify categories for tucnak2.desktop (Raspberry Pi Buster)
    become: yes
    lineinfile:
      path: /usr/share/applications/tucnak2.desktop
      regexp: '^Categories=Utility;HamRadio'
      line: Categories=HamRadio Logging
    when: is_rpi|bool and is_buster|bool

  - name: Install Tucnak (Raspberry Pi Bullseye)
    become: yes
    package:
      name: tucnak
      state: present
    when: is_rpi|bool and is_bullseye|bool

  - name: Modify categories for tucnak.desktop (Raspberry Pi Bullseye)
    become: yes
    lineinfile:
      path: /usr/share/applications/tucnak.desktop
      regexp: '^Categories=Utility;HamRadio'
      line: Categories=HamRadio Logging
    when: is_rpi|bool and is_bullseye|bool

#
# Install PyQSO
#

  - name: Install PyQSO library dependencies
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - gir1.2-gtk-3.0
      - python3-gi-cairo
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

# This module is missing a dependency, and I do not know how to resolve this:
# It is missing geos_c.h
#
#  - name: Download latest Cartopy from Git repo
#    git:
#      repo: https://github.com/SciTools/cartopy.git
#      dest: /home/{{ ham_user }}/hamradio/cartopy
#    retries: 5
#    delay: 30
#    register: result
#    until: result.failed == false

  - name: Install Python module - Cython
    become: yes
    command: pip3 install cython
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install Python module - sphinx
    become: yes
    command: pip3 install sphinx
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install Python module - numpy
    become: yes
    command: pip3 install numpy
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install Python module - matplotlib>=1.3.0
    become: yes
    command: pip3 install matplotlib>=1.3.0
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install Python module - cairocffi
    become: yes
    command: pip3 install cairocffi
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install Python module - geocoder
    become: yes
    command: pip3 install geocoder
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

# This module is fouled up. Keep getting errors about missing

#  - name: Install Python module - cartopy>=0.16.0
#    become: yes
#    command: pip3 install cartopy>=0.16.0
#    retries: 5
#    delay: 30
#    register: result
#    until: result.failed == false

  - name: Download latest PyQSO from Git repo
    git:
      repo: https://github.com/ctjacobs/pyqso.git
      dest: /home/{{ ham_user }}/hamradio/pyqso
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

# Doing this manually for now due to fouled up cartopy module
#  - name: Install PyQSO module dependencies
#    become: yes
#    command: pip3 install -U -r requirements.txt
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/pyqso

  - name: Install PyQSO systemwide
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/pyqso

  - name: Copy pyqso desktop file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/local/share/applications/pyqso.desktop"
      dest: "/usr/local/share/applications/pyqso.desktop"

  - name: Remove pyqso source directory
    file:
      path: /home/{{ ham_user }}/hamradio/pyqso
      state: absent

# Todo:
# twlog - basic logging program for ham radio
