#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

---

- name: HamPi 64-bit / HamPC v2.1 (March 2021) Playbook by W3DJS
  hosts: all
  # hosts: nuc
  # hosts: vm
  # hosts: hardware
  pre_tasks:
    - name: Verify Ansible meets HamPi / HamPC version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.9 to install this version of HamPi / HamPC by W3DJS."

- import_playbook: ../library/set_facts.yml
- import_playbook: init_task.yml
- import_playbook: configuration_tasks.yml
- import_playbook: install_menus.yml
- import_playbook: install_wallpaper.yml
- import_playbook: upgrade_debian_packages.yml
- import_playbook: install_bookmarks.yml
- import_playbook: install_cmake.yml
- import_playbook: install_wxwidgets.yml
# ^^^ This part takes about 1 hour to build on a RPi 4 ^^^

#
# Support both conventional and software-defined radios
#
- import_playbook: install_hamlib.yml
- import_playbook: install_rtaudio.yml
- import_playbook: include_DRAWS_support.yml
- import_playbook: install_ambeserver.yml
- import_playbook: install_airspy.yml
- import_playbook: install_airspyhf.yml
- import_playbook: install_soapy_sdr.yml
- import_playbook: install_soapy_audio.yml
- import_playbook: install_soapy_multi.yml
- import_playbook: install_soapy_netsdr.yml
- import_playbook: install_soapy_remote.yml
- import_playbook: install_soapy_airspy.yml
- import_playbook: install_soapy_airspyhf.yml
- import_playbook: install_soapy_bladeRF.yml
- import_playbook: install_soapy_fcdpp.yml
- import_playbook: install_soapy_hackrf.yml
- import_playbook: install_soapy_osmo.yml
- import_playbook: install_soapy_plutosdr.yml
- import_playbook: install_soapy_redpitaya.yml
- import_playbook: install_soapy_rtlsdr.yml
# Fails to build under aarch64:
- import_playbook: install_soapy_sdrplay3.yml
# Fails to build under aarch64:
- import_playbook: install_soapy_volkconverters.yml
# ^^^ This part takes about 1 hour, 15 minutes to build on a RPi 4 ^^^
- import_playbook: install_soapy_uhd.yml
# ^^^ UHD / SoapyUHD takes about 45 minutes to build on a RPi 4 ^^^

#
# FLDigi Suite
#
- import_playbook: install_flxmlrpc.yml
- import_playbook: install_flrig.yml
- import_playbook: install_fldigi.yml
- import_playbook: install_flaa.yml
- import_playbook: install_flamp.yml
- import_playbook: install_flcluster.yml
- import_playbook: install_fllog.yml
- import_playbook: install_flmsg.yml
- import_playbook: install_flnet.yml
- import_playbook: install_flpost.yml
- import_playbook: install_flwkey.yml
- import_playbook: install_flwrap.yml
# ^^^ This part takes about 20 minutes to build on a RPi 4 ^^^

#
# Ham Radio Applications
#
- import_playbook: install_adifmerg.yml
- import_playbook: install_antenna_modeling_apps.yml
- import_playbook: install_aprs_apps.yml
- import_playbook: install_d-rats_maurizioandreotti.yml
- import_playbook: install_echolink_apps.yml
- import_playbook: install_ham_training_apps.yml
- import_playbook: install_logging_apps.yml
- import_playbook: install_lopora.yml
- import_playbook: install_morsecode_apps.yml
- import_playbook: install_satellite_tracking.yml
- import_playbook: install_wsjtx.yml
# Fails to build under aarch64:
- import_playbook: install_js8call.yml
- import_playbook: install_js8callutilities.yml
# Fails to build under aarch64:
- import_playbook: install_jtdx.yml
- import_playbook: download_country_files.yml
- import_playbook: install_gridtracker.yml
- import_playbook: install_digital_apps.yml
- import_playbook: install_miscellaneous_apps.yml
- import_playbook: install_ax25.yml
- import_playbook: install_linpac.yml
- import_playbook: install_bluedv.yml
- import_playbook: install_chirp.yml
- import_playbook: install_pat.yml
- import_playbook: install_ardop_utils.yml
- import_playbook: install_HamClock_by_WB0OEW.yml
- import_playbook: install_qsstv.yml
- import_playbook: install_quisk.yml
- import_playbook: install_pmon.yml
- import_playbook: install_pybombs.yml
- import_playbook: install_tqsl.yml
- import_playbook: install_boinc.yml
- import_playbook: install_qslware.yml
- import_playbook: install_twclock.yml
- import_playbook: install_twhamqth.yml
- import_playbook: install_wxtoimg.yml
- import_playbook: install_freedv.yml
- import_playbook: install_dump1090.yml
- import_playbook: install_acarsdec.yml
# Fails to build under aarch64:
- import_playbook: install_voacapl.yml
- import_playbook: install_openwebrx.yml
- import_playbook: install_tapr_wspr.yml
- import_playbook: install_dxspider.yml
# OpenDV git repository has some issues, but
# some of them have been worked around.
- import_playbook: install_opendv.yml
- import_playbook: install_rpitx.yml
- import_playbook: install_leansdr.yml
- import_playbook: install_cygnusRFI.yml
- import_playbook: install_uhrr.yml
# Build broken on AMD64 by change to glibc:
- import_playbook: install_qrsspig.yml
- import_playbook: install_skcclogger.yml
- import_playbook: install_radioexplorer.yml
- import_playbook: install_reverse_beacon_network_client.yml
- import_playbook: install_qdmr_gui_dmr_radio_programmer.yml
- import_playbook: install_wfview.yml
- import_playbook: install_droidstar.yml
- import_playbook: install_ladyheather.yml
- import_playbook: install_cqrprop.yml
- import_playbook: install_tentenqsologger.yml

# Install SDR GUI apps after all pre-requisite SDR drivers are installed
- import_playbook: install_cutesdr.yml
- import_playbook: install_gqrx.yml
- import_playbook: install_lysdr.yml
- import_playbook: install_cubicsdr.yml
- import_playbook: install_sdrplusplus.yml

#- import_playbook: install_sdrangel.yml
# ^^^ SDRAngel takes about 65 minutes to build on a RPi 4 and 42 minutes on a x86_64 ^^^

# Final tasks
- import_playbook: finish_tasks.yml

#- import_playbook: terminate_ansible_early.yml

#Hold- import_playbook: install_teamviewer_host.yml

# Enable when they finally support Raspberry Pi
#Hold- import_playbook: install_sparksdr.yml
