#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Upgrade Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Update all packages to the latest version
    become: yes
    apt:
      upgrade: dist
    retries: 10
    delay: 30
    register: result
    until: result.failed == false

  - name: Autoremove unneeded packages
    become: yes
    apt:
      autoremove: yes

  - name: Remove unneeded packages from the cache
    become: yes
    apt:
      autoclean: yes
